#!/usr/bin/env python3
"""Generate German ARB translation from Italian source."""
import json
import sys

with open('lib/l10n/app_it.arb', 'r', encoding='utf-8') as f:
    it_data = json.load(f)

# Build German translations
de_data = {"@@locale": "de"}

# Translation map: Italian key -> German value
# We process every key. Metadata keys (@key) are copied as-is.
translations = {
    "smartTodoListOrigin": "Zugehörige Liste",
    "smartTodoSortTooltip": "Sortieroptionen",
    "smartTodoSortManual": "Manuell",
    "smartTodoSortDate": "Neueste",
    "smartTodoActionSortPriority": "Nach Priorität sortieren",
    "smartTodoActionSortDeadline": "Nach Fälligkeitsdatum sortieren",
    "smartTodoOrderUpdated": "Reihenfolge manuell aktualisiert",
    "newRetro": "Neue Retro",
    "appTitle": "Keisen",
    "goToHome": "Zur Startseite",
    "actionSave": "Speichern",
    "actionCancel": "Abbrechen",
    "actionDelete": "Löschen",
    "actionEdit": "Bearbeiten",
    "actionCreate": "Erstellen",
    "actionAdd": "Hinzufügen",
    "actionClose": "Schließen",
    "actionHide": "Karten ausblenden",
    "actionRetry": "Erneut versuchen",
    "exportAllData": "Alle Daten exportieren (Vollständiger Bericht)",
    "actionConfirm": "Bestätigen",
    "actionSearch": "Suchen",
    "actionFilter": "Filtern",
    "actionExport": "Exportieren",
    "actionExportCsv": "CSV exportieren",
    "retroBoard": "Board-Elemente",
    "actionCopy": "Kopieren",
    "actionShare": "Teilen",
    "actionDone": "Fertig",
    "actionReset": "Zurücksetzen",
    "actionOpen": "Öffnen",
    "stateLoading": "Wird geladen...",
    "stateEmpty": "Keine Elemente",
    "stateError": "Fehler",
    "stateSuccess": "Erfolg",
    "subscriptionCurrent": "AKTUELL",
    "subscriptionRecommended": "EMPFOHLEN",
    "subscriptionFree": "Kostenlos",
    "subscriptionPerMonth": "/Monat",
    "subscriptionPerYear": "/Jahr",
    "subscriptionSaveYearly": "Sie sparen €{amount}/Jahr",
    "subscriptionTrialDays": "{days} Tage kostenlose Testphase",
    "subscriptionUnlimitedProjects": "Unbegrenzte Projekte",
    "subscriptionProjectsActive": "{count} aktive Projekte",
    "subscriptionUnlimitedLists": "Unbegrenzte Listen",
    "subscriptionSmartTodoLists": "Smart Todo Listen",
    "subscriptionActiveProjectsLabel": "Aktive Projekte",
    "subscriptionSmartTodoListsLabel": "Smart Todo Listen",
    "subscriptionUnlimitedTasks": "Unbegrenzte Tasks",
    "subscriptionTasksPerProject": "{count} Tasks pro Projekt",
    "subscriptionUnlimitedInvites": "Unbegrenzte Einladungen",
    "subscriptionInvitesPerProject": "{count} Einladungen pro Projekt",
    "subscriptionWithAds": "Mit Werbung",
    "subscriptionWithoutAds": "Ohne Werbung",
    "authSignInGoogle": "Mit Google anmelden",
    "authSignOut": "Abmelden",
    "authLogoutConfirm": "Sind Sie sicher, dass Sie sich abmelden möchten?",
    "formNameRequired": "Bitte geben Sie Ihren Namen ein",
    "authError": "Authentifizierungsfehler",
    "authUserNotFound": "Benutzer nicht gefunden",
    "authWrongPassword": "Falsches Passwort",
    "authEmailInUse": "E-Mail bereits in Verwendung",
    "authWeakPassword": "Passwort zu schwach",
    "authInvalidEmail": "Ungültige E-Mail-Adresse",
    "appSubtitle": "Keisen für Teams",
    "authOr": "oder",
    "authPassword": "Passwort",
    "authRegister": "Registrieren",
    "authLogin": "Anmelden",
    "authHaveAccount": "Sie haben bereits ein Konto?",
    "authNoAccount": "Sie haben noch kein Konto?",
    "authForgotPassword": "Passwort vergessen?",
    "authResetPasswordSent": "E-Mail zum Zurücksetzen gesendet. Überprüfen Sie Ihr Postfach.",
    "authVerifyEmail": "Bestätigen Sie Ihre E-Mail",
    "authVerifyEmailDesc": "Wir haben Ihnen eine Bestätigungs-E-Mail an {email} gesendet. Klicken Sie auf den Link, um Ihr Konto zu aktivieren.",
    "authResendVerification": "Bestätigungs-E-Mail erneut senden",
    "authVerificationSent": "Bestätigungs-E-Mail gesendet!",
    "authEmailVerified": "E-Mail bestätigt!",
    "authIVerified": "Ich habe meine E-Mail bestätigt",
    "authWaitingVerification": "Warten auf Bestätigung...",
    "authChangePassword": "Passwort ändern",
    "authCurrentPassword": "Aktuelles Passwort",
    "authNewPassword": "Neues Passwort",
    "authConfirmNewPassword": "Neues Passwort bestätigen",
    "authPasswordChanged": "Passwort erfolgreich geändert",
    "authPasswordMismatch": "Passwörter stimmen nicht überein",
    "authPasswordTooShort": "Mindestens 6 Zeichen",
    "authReauthRequired": "Bestätigen Sie Ihre Identität",
    "authReauthDesc": "Aus Sicherheitsgründen bestätigen Sie bitte Ihre Identität, um fortzufahren.",
    "authSignInWithEmail": "Mit E-Mail anmelden",
    "authWrongCurrentPassword": "Das aktuelle Passwort ist nicht korrekt",
    "profileSecurity": "Sicherheit",
    "authCooldownWait": "Warten Sie {seconds}s, bevor Sie erneut senden",
    "navHome": "Startseite",
    "navProfile": "Profil",
    "navSettings": "Einstellungen",
    "eisenhowerTitle": "Eisenhower-Matrix",
    "eisenhowerYourMatrices": "Ihre Matrizen",
    "eisenhowerNoMatrices": "Keine Matrizen erstellt",
    "eisenhowerNewMatrix": "Neue Matrix",
    "eisenhowerViewGrid": "Raster",
    "eisenhowerViewChart": "Diagramm",
    "eisenhowerViewList": "Liste",
    "eisenhowerViewRaci": "RACI",
    "quadrantUrgent": "DRINGEND",
    "quadrantNotUrgent": "NICHT DRINGEND",
    "quadrantImportant": "WICHTIG",
    "quadrantNotImportant": "NICHT WICHTIG",
    "quadrantQ1Title": "SOFORT ERLEDIGEN",
    "quadrantQ2Title": "PLANEN",
    "quadrantQ3Title": "DELEGIEREN",
    "quadrantQ4Title": "ELIMINIEREN",
    "quadrantQ1Subtitle": "Dringend und Wichtig",
    "quadrantQ2Subtitle": "Wichtig, Nicht Dringend",
    "quadrantQ3Subtitle": "Dringend, Nicht Wichtig",
    "quadrantQ4Subtitle": "Nicht Dringend, Nicht Wichtig",
    "eisenhowerNoActivities": "Keine Aktivitäten",
    "eisenhowerNewActivity": "Neue Aktivität",
    "eisenhowerExportSheets": "Nach Google Sheets exportieren",
    "eisenhowerInviteParticipants": "Teilnehmer einladen",
    "eisenhowerDeleteMatrix": "Matrix löschen",
    "eisenhowerDeleteMatrixConfirm": "Sind Sie sicher, dass Sie diese Matrix löschen möchten?",
    "eisenhowerActivityTitle": "Aktivitätstitel",
    "eisenhowerActivityNotes": "Notizen",
    "eisenhowerDueDate": "Fälligkeitsdatum",
    "eisenhowerPriority": "Priorität",
    "eisenhowerAssignee": "Zuständig",
    "eisenhowerCompleted": "Abgeschlossen",
    "eisenhowerMoveToQuadrant": "In Quadrant verschieben",
    "eisenhowerMatrixSettings": "Matrix-Einstellungen",
    "eisenhowerBackToList": "Liste",
    "eisenhowerPriorityList": "Prioritätsliste",
    "eisenhowerAllActivities": "Alle Aktivitäten",
    "eisenhowerToVote": "Noch abzustimmen",
    "eisenhowerVoted": "Abgestimmt",
    "eisenhowerTotal": "Gesamt",
    "eisenhowerEditParticipants": "Teilnehmer bearbeiten",
    "eisenhowerActivityCountLabel": "{count} Aktivitäten",
    "eisenhowerVoteCountLabel": "{count} Stimmen",
    "eisenhowerModifyVotes": "Stimmen ändern",
    "eisenhowerSaving": "Speichern...",
    "eisenhowerSaveChanges": "Änderungen speichern",
    "eisenhowerSavedSuccessfully": "Änderungen erfolgreich gespeichert",
    "eisenhowerErrorSaving": "Fehler beim Speichern",
    "eisenhowerEnterTitle": "Geben Sie einen Titel ein",
    "eisenhowerTitleHint": "Aktivitätstitel eingeben",
    "eisenhowerNotesHint": "Optionale Notizen",
    "eisenhowerTitleRequired": "Titel ist erforderlich",
    "eisenhowerDeleteActivity": "Aktivität löschen",
    "eisenhowerDeleteActivityConfirm": "Sind Sie sicher, dass Sie diese Aktivität löschen möchten?",
    "eisenhowerNewMatrixName": "Matrixname",
    "eisenhowerNewMatrixNameHint": "Geben Sie einen Namen ein",
    "eisenhowerNewMatrixNameRequired": "Name ist erforderlich",
    "estimationTitle": "Estimation Room",
    "estimationYourSessions": "Ihre Sitzungen",
    "estimationNoSessions": "Keine Schätzsitzungen",
    "estimationNewSession": "Neue Sitzung",
    "estimationSessionName": "Sitzungsname",
    "estimationSessionNameHint": "z.B. Sprint 12 Planung",
    "estimationDeckType": "Kartenset",
    "estimationDeckFibonacci": "Fibonacci (1, 2, 3, 5, 8...)",
    "estimationDeckTShirt": "T-Shirt-Größen (XS-XXL)",
    "estimationDeckCustom": "Benutzerdefiniert",
    "estimationParticipants": "Teilnehmer",
    "estimationStories": "Stories",
    "estimationNoStories": "Keine Stories",
    "estimationNewStory": "Neue Story",
    "estimationStoryTitle": "Story-Titel",
    "estimationStoryDescription": "Beschreibung",
    "estimationVote": "Abstimmen",
    "estimationRevealVotes": "Stimmen aufdecken",
    "estimationResetVotes": "Stimmen zurücksetzen",
    "estimationAverage": "Durchschnitt",
    "estimationConsensus": "Konsens",
    "estimationNoConsensus": "Kein Konsens",
    "estimationFinalEstimate": "Endschätzung",
    "estimationAcceptEstimate": "Schätzung akzeptieren",
    "estimationHistory": "Verlauf",
    "estimationExport": "Ergebnisse exportieren",
    "estimationTimer": "Timer",
    "estimationTimerStart": "Timer starten",
    "estimationTimerStop": "Timer stoppen",
    "estimationTimerReset": "Timer zurücksetzen",
    "errorGeneric": "Fehler: {error}",
    "deleteConfirm": "Löschen bestätigen",
    "deleteConfirmMessage": "Sind Sie sicher, dass Sie löschen möchten?",
    "homeWelcome": "Willkommen",
    "homeNoItems": "Keine Elemente vorhanden",
    "profileTitle": "Profil",
    "profileDisplayName": "Anzeigename",
    "profileEmail": "E-Mail",
    "profilePhotoUrl": "Foto-URL",
    "profileSave": "Profil speichern",
    "profileSaved": "Profil gespeichert",
    "profileDeleteAccount": "Konto löschen",
    "profileDeleteAccountConfirmTitle": "Konto löschen",
    "settingsTitle": "Einstellungen",
    "settingsLanguage": "Sprache",
    "settingsTheme": "Design",
    "settingsThemeLight": "Hell",
    "settingsThemeDark": "Dunkel",
    "settingsThemeSystem": "System",
    "settingsNotifications": "Benachrichtigungen",
    "pokemonMode": "Scrum-Karten",
    "pokemonModeDesc": "Kartenset für die Estimation Room",
    "pokemonModeClassic": "Klassisch",
    "pokemonModeAnimal": "Tiere",
    "estimationRoomTitle": "Estimation Room",
    "estimationMode": "Schätzmethode",
    "estimationModePoker": "Planning Poker",
    "estimationModeTShirt": "T-Shirt Sizing",
    "estimationModeDecimal": "Dezimal (Tage)",
    "estimationModeThreePoint": "Drei-Punkt (PERT)",
    "sessionCreatedDate": "Erstellt am {date}",
    "sessionStatus": "Status: {status}",
    "sessionStatusDraft": "Entwurf",
    "sessionStatusActive": "Aktiv",
    "sessionStatusCompleted": "Abgeschlossen",
    "pokerMaxVoters": "Max. Abstimmende",
    "pokerNoLimit": "Kein Limit",
    "pokerVoters": "{count} Abstimmende",
    "storyEditTitle": "Story bearbeiten",
    "storyAddTitle": "Story hinzufügen",
    "storyTitleLabel": "Titel",
    "storyTitleHint": "Geben Sie den Story-Titel ein",
    "storyTitleRequired": "Titel ist erforderlich",
    "storyDescriptionLabel": "Beschreibung",
    "storyDescriptionHint": "Story-Beschreibung (optional)",
    "estimatedLabel": "Geschätzt",
    "notEstimatedLabel": "Nicht geschätzt",
    "averageLabel": "Durchschnitt",
    "sessionParticipantsLabel": "Teilnehmer ({count})",
    "facilitatorLabel": "Moderator",
    "observerLabel": "Beobachter",
    "voterLabel": "Abstimmender",
    "acceptEstimate": "Akzeptieren",
    "autoCalculate": "Automatisch berechnen",
    "estimatePoints": "{points} Punkte",
    "roundLabel": "Runde {round}",
    "revealVotes": "Aufdecken",
    "nextStory": "Nächste Story",
    "previousStory": "Vorherige Story",
    "skipStory": "Story überspringen",
    "sessionCompletedMessage": "Sitzung abgeschlossen!",
    "allStoriesEstimated": "Alle Stories geschätzt",
    "storiesCount": "{estimated}/{total} geschätzt",
    "startSession": "Sitzung starten",
    "endSession": "Sitzung beenden",
    "sessionSettings": "Sitzungseinstellungen",
    "timerDuration": "Timer-Dauer",
    "seconds": "Sekunden",
    "minutes": "Minuten",
    "showTimer": "Timer anzeigen",
    "autoReveal": "Automatisch aufdecken",
    "pokerCreatedBy": "Erstellt von: {name}",
    "deleteSession": "Sitzung löschen",
    "deleteSessionConfirm": "Sind Sie sicher, dass Sie diese Sitzung löschen möchten?",
    "deleteStory": "Story löschen",
    "deleteStoryConfirm": "Sind Sie sicher, dass Sie diese Story löschen möchten?",
    "sessionNameRequired": "Sitzungsname ist erforderlich",
    "noParticipants": "Keine Teilnehmer",
    "inviteParticipants": "Teilnehmer einladen",
    "copySessionLink": "Sitzungslink kopieren",
    "sessionLinkCopied": "Sitzungslink kopiert!",
    "shareSession": "Sitzung teilen",
    "estimationComplete": "Schätzung abgeschlossen",
    "currentlyVoting": "Aktuelle Abstimmung",
    "waitingForVotes": "Warte auf Stimmen...",
    "votingComplete": "Abstimmung abgeschlossen",
    "yourVote": "Ihre Stimme",
    "changeVote": "Stimme ändern",
    "confirmVote": "Stimme bestätigen",
    "discussResults": "Ergebnisse besprechen",
    "newRound": "Neue Runde",
    "finalEstimate": "Endschätzung: {points}",
    "consensusReached": "Konsens erreicht",
    "noConsensusReached": "Kein Konsens - Diskussion empfohlen",
    "estimationSummary": "Schätzübersicht",
    "totalPoints": "Gesamtpunkte: {points}",
    "averagePoints": "Durchschnittspunkte: {points}",
    "sessionDuration": "Sitzungsdauer: {duration}",
    "exportResults": "Ergebnisse exportieren",
    "shareResults": "Ergebnisse teilen",
    "backToSessions": "Zurück zu Sitzungen",
    "estimationDeckModFibonacci": "Modifizierte Fibonacci (0, 1, 2, 3, 5, 8, 13, 20, 40, 100)",
    "estimationDeckPowerOf2": "Potenz von 2 (1, 2, 4, 8, 16, 32, 64)",
    "estimationDeckSequential": "Sequenziell (1-10)",
    "customDeckLabel": "Benutzerdefiniertes Kartenset",
    "addCustomValue": "Wert hinzufügen",
    "customValueHint": "z.B. 0.5",
    "reorderStories": "Stories neu ordnen",
    "bulkImportStories": "Stories massenhaft importieren",
    "importFromText": "Aus Text importieren",
    "importTextHint": "Eine Story pro Zeile eingeben",
    "importCount": "{count} Stories importiert",
    "pokerSessionActive": "Die Sitzung ist aktiv!",
    "pokerRoomSettings": "Raumeinstellungen",
    "pokerShowAverage": "Durchschnitt anzeigen",
    "pokerAllowRevote": "Erneutes Abstimmen erlauben",
    "pokerAutoFlip": "Automatisch aufdecken, wenn alle abgestimmt haben",
    "pokerCardStyle": "Kartenstil",
    "pokerCardStyleMinimal": "Minimalistisch",
    "pokerCardStyleClassic": "Klassisch",
    "pokerCardStyleFun": "Spaßig",
    "pokerSpectatorMode": "Beobachtermodus",
    "pokerSpectatorModeDesc": "Sie sehen die Abstimmung, können aber nicht abstimmen",
    "pokerConnectionStatus": "Verbindungsstatus",
    "pokerConnected": "Verbunden",
    "pokerDisconnected": "Getrennt",
    "pokerReconnecting": "Verbindung wird wiederhergestellt...",
    "sessionAnalytics": "Sitzungsanalyse",
    "votingPatterns": "Abstimmungsmuster",
    "estimationAccuracy": "Schätzgenauigkeit",
    "velocityTrend": "Velocity-Trend",
    "retroTitle": "Retrospektive",
    "retroYourRetros": "Ihre Retrospektiven",
    "retroNoRetros": "Keine Retrospektiven",
    "retroNewRetro": "Neue Retrospektive",
    "retroTemplate": "Vorlage",
    "retroTemplateStartStopContinue": "Start / Stop / Continue",
    "retroTemplateMadSadGlad": "Mad / Sad / Glad",
    "retroTemplate4Ls": "4L's (Liked, Learned, Lacked, Longed For)",
    "retroTemplateSailboat": "Sailboat",
    "retroTemplateCustom": "Benutzerdefiniert",
    "retroPhaseWrite": "Schreiben",
    "retroPhaseVote": "Abstimmen",
    "retroPhaseDiscuss": "Diskutieren",
    "retroPhaseAction": "Aktionen",
    "retroAddCard": "Karte hinzufügen",
    "retroDeleteCard": "Karte löschen",
    "retroLikeCard": "Karte liken",
    "retroMoveCard": "Karte verschieben",
    "retroActionItem": "Aktionspunkt",
    "retroNewActionItem": "Neuer Aktionspunkt",
    "retroActionItemTitle": "Titel",
    "retroActionItemAssignee": "Zuständig",
    "retroActionItemDueDate": "Fälligkeitsdatum",
    "retroActionItemStatus": "Status",
    "retroActionItemStatusOpen": "Offen",
    "retroActionItemStatusInProgress": "In Bearbeitung",
    "retroActionItemStatusDone": "Erledigt",
    "retroEditCard": "Karte bearbeiten",
    "retroCardText": "Kartentext",
    "retroVotesRemaining": "Verbleibende Stimmen: {count}",
    "retroTotalVotes": "Stimmen gesamt: {count}",
    "retroSortByVotes": "Nach Stimmen sortieren",
    "retroGroupCards": "Karten gruppieren",
    "retroUngroupCards": "Karten aufheben",
    "retroExportPDF": "Als PDF exportieren",
    "retroExportCSV": "Als CSV exportieren",
    "retroShareLink": "Link teilen",
    "retroTimerMinutes": "{minutes} Minuten pro Phase",
    "retroCompleted": "Retrospektive abgeschlossen",
    "retroInProgress": "Retrospektive läuft",
    "retroNotStarted": "Nicht gestartet",
    "retroFacilitator": "Moderator",
    "retroParticipantCount": "{count} Teilnehmer",
    "retroStartPhase": "Phase starten",
    "retroNextPhase": "Nächste Phase",
    "retroPreviousPhase": "Vorherige Phase",
    "retroEndRetro": "Retrospektive beenden",
    "retroSummary": "Zusammenfassung",
    "retroActionItems": "Aktionspunkte ({count})",
    "retroTopVotedItems": "Meistgewählte Punkte",
    "retroParticipation": "Teilnahme: {count} aktive Teilnehmer",
    "retroDeleteConfirm": "Sind Sie sicher, dass Sie diese Retrospektive löschen möchten?",
    "retroColumnWentWell": "Was gut lief",
    "retroColumnToImprove": "Was zu verbessern ist",
    "retroColumnActionItems": "Aktionspunkte",
    "retroColumnMad": "Mad",
    "retroColumnSad": "Sad",
    "retroColumnGlad": "Glad",
    "retroColumnLiked": "Liked",
    "retroColumnLearned": "Learned",
    "retroColumnLacked": "Lacked",
    "retroColumnWind": "Wind (Unterstützung)",
    "retroColumnAnchor": "Anker (Hindernisse)",
    "retroColumnRock": "Felsen (Risiken)",
    "retroColumnGoal": "Insel (Ziele)",
    "retroColumnDrop": "Drop",
    "retroColumnAdd": "Add",
    "retroColumnKeep": "Keep",
    "retroColumnImprove": "Improve",
    "retroColumnMore": "Mehr",
    "retroColumnLess": "Weniger",
    "retroTemplateWentWellToImprove": "Went Well / To Improve",
    "retroTemplateDAKI": "DAKI (Drop, Add, Keep, Improve)",
    "retroTemplateStarfish": "Starfish (More, Less, Keep, Stop, Start)",
    "retroColumnStarfishKeep": "Keep",
    "retroColumnStarfishMore": "Mehr",
    "retroColumnStarfishLess": "Weniger",
    "retroColumnStarfishStop": "Stop",
    "retroColumnStarfishStart": "Start",
    "homeQuickActions": "Schnellaktionen",
    "homeCreateEisenhower": "Neue Matrix",
    "homeCreateEstimation": "Neue Sitzung",
    "homeCreateRetro": "Neue Retrospektive",
    "homeCreateSmartTodo": "Neue Liste",
    "homeRecentActivity": "Letzte Aktivitäten",
    "homeNoRecentActivity": "Keine letzten Aktivitäten",
    "homeMyEisenhower": "Meine Matrizen",
    "homeMyEstimation": "Meine Sitzungen",
    "homeMyRetro": "Meine Retrospektiven",
    "homeMySmartTodo": "Meine Listen",
    "homeToolEisenhower": "Eisenhower-Matrix",
    "homeToolEstimation": "Estimation Room",
    "homeToolRetro": "Retrospektive",
    "homeToolSmartTodo": "Smart Todo",
    "homeSeeAll": "Alle anzeigen",
    "homeEmptyState": "Erstellen Sie Ihr erstes Projekt, um zu beginnen!",
    "smartTodoTitle": "Smart Todo",
    "smartTodoNoLists": "Keine Listen erstellt",
    "smartTodoNewList": "Neue Liste",
    "smartTodoListName": "Listenname",
    "smartTodoListNameHint": "z.B. Sprint Backlog",
    "smartTodoTaskTitle": "Task-Titel",
    "smartTodoTaskDescription": "Beschreibung",
    "smartTodoTaskPriority": "Priorität",
    "smartTodoTaskDueDate": "Fälligkeitsdatum",
    "smartTodoTaskAssignee": "Zuständig",
    "smartTodoDeleteList": "Liste löschen",
    "smartTodoDeleteListConfirm": "Sind Sie sicher, dass Sie diese Liste löschen möchten?",
    "smartTodoDeleteTask": "Task löschen",
    "smartTodoDeleteTaskConfirm": "Sind Sie sicher, dass Sie diesen Task löschen möchten?",
    "smartTodoTaskStatus": "Status",
    "smartTodoTaskStatusTodo": "Zu erledigen",
    "smartTodoTaskStatusInProgress": "In Bearbeitung",
    "smartTodoTaskStatusDone": "Erledigt",
    "smartTodoCompleted": "{count} abgeschlossen",
    "smartTodoProgress": "{completed}/{total} erledigt",
    "smartTodoCreatedBy": "Erstellt von: {name}",
    "homeMyAgileProjects": "Meine Agile Projekte",
    "homeCreateAgileProject": "Neues Agile Projekt",
    "homeToolAgileProject": "Agile Projekt",
    "agileNoProjects": "Keine Agile Projekte",
    "agileCreateProject": "Projekt erstellen",
    "agileProjectTitle": "Agile Projekt",
    "agileBacklog": "Backlog",
    "agileSprint": "Sprint",
    "agileBoard": "Board",
    "agileMetrics": "Metriken",
    "agileTeam": "Team",
    "agileRetro": "Retrospektive",
    "agileUserStory": "User Story",
    "agileUserStories": "User Stories",
    "agileKanbanItems": "Kanban Items",
    "agileScrumban": "Scrumban",
    "agileNewSprint": "Neuer Sprint",
    "agileSprintName": "Sprint-Name",
    "agileSprintGoal": "Sprint-Ziel",
    "agileSprintStart": "Startdatum",
    "agileSprintEnd": "Enddatum",
    "agileStartSprint": "Sprint starten",
    "agileEndSprint": "Sprint beenden",
    "agileSprintActive": "Aktiver Sprint",
    "agileSprintCompleted": "Abgeschlossener Sprint",
    "agileSprintPlanning": "Sprint-Planung",
    "agileNoSprints": "Keine Sprints",
    "agileSprintBacklog": "Sprint Backlog",
    "agileVelocity": "Velocity",
    "agileBurndown": "Burndown",
    "agileAddToSprint": "Zum Sprint hinzufügen",
    "agileRemoveFromSprint": "Aus Sprint entfernen",
    "agileStoryPoints": "Story Points",
    "agileStatus": "Status",
    "agileStatusTodo": "Zu erledigen",
    "agileStatusInProgress": "In Bearbeitung",
    "agileStatusDone": "Erledigt",
    "agileStatusBlocked": "Blockiert",
    "agileKanbanBoard": "Kanban Board",
    "agileKanbanColumns": "Kanban-Spalten",
    "agileAddColumn": "Spalte hinzufügen",
    "agileWipLimit": "WIP-Limit",
    "agileWipLimitHint": "Max. Items in dieser Spalte",
    "agileWipExceeded": "WIP-Limit überschritten!",
    "agileMoveToColumn": "In Spalte verschieben",
    "agileFilterByAssignee": "Nach Zuständigem filtern",
    "agileFilterByPriority": "Nach Priorität filtern",
    "agileFilterByTag": "Nach Tag filtern",
    "agileSortBy": "Sortieren nach",
    "agileSortByPriority": "Priorität",
    "agileSortByPoints": "Story Points",
    "agileSortByDate": "Erstellungsdatum",
    "agileSortByTitle": "Titel",
    "agileClearFilters": "Filter zurücksetzen",
    "agilePriorityLabel": "Priorität",
    "agileTagsLabel": "Tags",
    "agileNoTasks": "Keine Tasks",
    "agileDescription": "Beschreibung",
    "agileDependency": "Abhängigkeit",
    "agileDependencyAdd": "Abhängigkeit hinzufügen",
    "agileDependencyBlockedBy": "Blockiert von",
    "agileDependencyBlocks": "Blockiert",
    "agileDependencyNone": "Keine Abhängigkeiten",
    "agileNotifications": "Benachrichtigungen",
    "agileNotificationNewStory": "Neue Story erstellt",
    "agileNotificationSprintStarted": "Sprint gestartet",
    "agileNotificationSprintCompleted": "Sprint abgeschlossen",
    "agileLeadTime": "Lead Time",
    "agileCycleTime": "Cycle Time",
    "agileThroughput": "Throughput",
    "agileDistribution": "Verteilung",
    "agileCfd": "CFD",
    "agileMetricsTitle": "Metriken & Analyse",
    "agileNoMetrics": "Keine verfügbaren Metriken",
    "agileCompleteSprintFirst": "Schließen Sie mindestens einen Sprint ab",
    "agileVelocityChart": "Velocity-Diagramm",
    "agileAverageVelocity": "Durchschnittliche Velocity: {velocity}",
    "agileBurndownChart": "Burndown-Diagramm",
    "agileTeamTitle": "Team",
    "agileTeamMembers": "Teammitglieder",
    "agileAddTeamMember": "Mitglied hinzufügen",
    "agileRemoveTeamMember": "Mitglied entfernen",
    "agileRole": "Rolle",
    "agileInviteByEmail": "Per E-Mail einladen",
    "agileTeamActivity": "Team-Aktivität",
    "agileGuideTitle": "Agile-Leitfaden",
    "agileGuideScrum": "Scrum-Leitfaden",
    "agileGuideKanban": "Kanban-Leitfaden",
    "agileGuideScrumDesc": "Scrum ist ein agiles Framework, das Arbeit in Iterationen fester Länge namens Sprints organisiert.",
    "agileGuideKanbanDesc": "Kanban ist eine Methode zur Visualisierung und Verwaltung des Arbeitsflusses mithilfe von Karten auf einem Board.",
    "agileGuideScrumRoles": "Scrum-Rollen: Product Owner, Scrum Master, Development Team",
    "agileGuideScrumEvents": "Scrum-Events: Sprint Planning, Daily Scrum, Sprint Review, Retrospektive",
    "agileGuideScrumArtifacts": "Scrum-Artefakte: Product Backlog, Sprint Backlog, Increment",
    "agileGuideKanbanPrinciples": "Kanban-Prinzipien: Arbeit visualisieren, WIP begrenzen, Fluss steuern",
    "agileGuideKanbanMetrics": "Kanban-Metriken: Lead Time, Cycle Time, Throughput, CFD",
    "estimationDeckTShirt": "T-Shirt-Größen (XS, S, M, L, XL, XXL)",
    "agileNotAssigned": "Nicht zugewiesen",
    "agileSearchStories": "Stories suchen...",
    "agileConfirmDeleteTitle": "Story löschen",
    "agileConfirmDeleteMessage": "Sind Sie sicher, dass Sie \"{title}\" löschen möchten?",
    "storyFormTitle": "Story-Titel",
    "storyFormTitleRequired": "Bitte geben Sie den Story-Titel ein",
    "storyFormDescription": "Beschreibung",
    "storyFormDescriptionHint": "Beschreiben Sie die Anforderung",
    "storyFormUseTemplate": "User Story-Vorlage verwenden",
    "storyFormTemplateSubtitle": "Als... möchte ich... damit...",
    "storyFormAsA": "Als...",
    "storyFormAsAHint": "Benutzer, Admin, Kunde...",
    "storyFormIWant": "Möchte ich...",
    "storyFormIWantHint": "etwas tun können...",
    "storyFormSoThat": "Damit...",
    "storyFormSoThatHint": "einen Nutzen erzielen...",
    "storyFormPreview": "Vorschau:",
    "storyFormEmptyDescription": "(leere Beschreibung)",
    "storyFormAcceptanceCriteria": "Akzeptanzkriterien",
    "storyFormAcceptanceCriteriaHint": "Definieren Sie, wann die Story als abgeschlossen gilt",
    "storyFormAddCriterion": "Kriterium hinzufügen...",
    "storyFormNoCriteria": "Keine Kriterien definiert",
    "storyFormSuggestion1": "Der Benutzer kann sich mit E-Mail und Passwort anmelden",
    "storyFormSuggestion2": "Die Daten werden im korrekten Format validiert",
    "storyFormSuggestion3": "Im Fehlerfall wird eine klare Meldung angezeigt",
    "storyFormSuggestion4": "Die Funktion ist auf Mobilgeräten zugänglich",
    "storyFormPriorityLabel": "Priorität (MoSCoW)",
    "storyFormBusinessValueLabel": "Business Value",
    "storyFormBusinessValueHigh": "Hoher Business Value",
    "storyFormBusinessValueMedium": "Mittlerer Wert",
    "storyFormBusinessValueLow": "Niedriger Business Value",
    "storyFormStoryPointsLabel": "In Story Points geschätzt",
    "storyFormStoryPointsTooltip": "Story Points stellen die relative Komplexität der Arbeit dar.\nVerwenden Sie die Fibonacci-Folge: 1 (einfach) -> 21 (sehr komplex).",
    "storyFormNoPoints": "Keine",
    "storyFormPointsSimple": "Schnelle und einfache Aufgabe",
    "storyFormPointsMedium": "Aufgabe mittlerer Komplexität",
    "storyFormPointsComplex": "Komplexe Aufgabe, erfordert Analyse",
    "storyFormPointsVeryComplex": "Sehr komplex, erwägen Sie die Story aufzuteilen",
    "storyFormTagsLabel": "Tags",
    "storyFormAddTagHint": "Tag hinzufügen...",
    "storyFormExistingTags": "Vorhandene Tags:",
    "storyFormAssigneeLabel": "Zuweisen an",
    "storyFormAssigneeHint": "Wählen Sie ein Teammitglied",
    "storyFormNotAssigned": "Nicht zugewiesen",
    "storyDetailPointsLabel": "{points} Punkte",
    "storyDetailDescriptionTitle": "Beschreibung",
    "storyDetailNoDescription": "Keine Beschreibung",
    "storyDetailAcceptanceCriteria": "Akzeptanzkriterien ({completed}/{total})",
    "storyDetailNoCriteria": "Keine Kriterien definiert",
    "storyDetailEstimationTitle": "Schätzung",
    "storyDetailFinalEstimate": "Endschätzung: ",
    "storyDetailEstimatesReceived": "{count} Schätzungen erhalten",
    "storyDetailInfoTitle": "Informationen",
    "storyDetailBusinessValue": "Business Value",
    "storyDetailAssignedTo": "Zugewiesen an",
    "storyDetailSprint": "Sprint",
    "storyDetailCreatedAt": "Erstellt am",
    "storyDetailStartedAt": "Gestartet am",
    "storyDetailCompletedAt": "Abgeschlossen am",
    "landingBadge": "Werkzeuge für agile Teams",
    "landingHeroTitle": "Build better products\nwith Keisen",
    "landingHeroSubtitle": "Priorisieren, schätzen und verwalten Sie Ihre Projekte mit kollaborativen Werkzeugen. Alles an einem Ort, kostenlos.",
    "landingStartFree": "Kostenlos starten",
    "landingEverythingNeed": "Alles, was Sie brauchen",
    "landingModernTools": "Werkzeuge für moderne Teams",
    "landingSmartTodoBadge": "Produktivität",
    "landingSmartTodoTitle": "Smart Todo List",
    "landingSmartTodoSubtitle": "Intelligentes und kollaboratives Taskmanagement für moderne Teams",
    "landingSmartTodoCollaborativeTitle": "Kollaborative Tasklisten",
    "landingSmartTodoCollaborativeDesc": "Smart Todo verwandelt das tägliche Aufgabenmanagement in einen fließenden und kollaborativen Prozess. Erstellen Sie Listen, weisen Sie Tasks Teammitgliedern zu und überwachen Sie den Fortschritt in Echtzeit.\n\nIdeal für verteilte Teams, die eine kontinuierliche Synchronisierung der zu erledigenden Aufgaben benötigen.",
    "landingSmartTodoImportTitle": "Flexibler Import",
    "landingSmartTodoImportDesc": "Importieren Sie Ihre Aufgaben aus externen Quellen mit wenigen Klicks. Unterstützung für CSV-Dateien, Kopieren/Einfügen aus Excel oder Freitext. Das System erkennt automatisch die Datenstruktur.\n\nMigrieren Sie einfach von anderen Tools, ohne Informationen zu verlieren oder jeden Task manuell eingeben zu müssen.",
    "landingSmartTodoShareTitle": "Teilen und Einladen",
    "landingSmartTodoShareDesc": "Laden Sie Kollegen und Mitarbeiter per E-Mail zu Ihren Listen ein. Jeder Teilnehmer kann die zugewiesenen Tasks anzeigen, kommentieren und den Status aktualisieren.\n\nPerfekt für die Verwaltung abteilungsübergreifender Projekte mit externen Stakeholdern oder funktionsübergreifenden Teams.",
    "landingSmartTodoFeaturesTitle": "Smart Todo Funktionen",
    "landingEisenhowerBadge": "Priorisierung",
    "landingEisenhowerSubtitle": "Die Entscheidungsmethode, die Führungskräfte zur Zeitplanung verwenden",
    "landingEisenhowerUrgentImportantTitle": "Dringend vs. Wichtig",
    "landingEisenhowerUrgentImportantDesc": "Die Eisenhower-Matrix, entwickelt vom 34. Präsidenten der Vereinigten Staaten Dwight D. Eisenhower, teilt Aktivitäten in vier Quadranten basierend auf zwei Kriterien ein: Dringlichkeit und Wichtigkeit.\n\nDieses Entscheidungsframework hilft zu unterscheiden, was sofortige Aufmerksamkeit erfordert und was zu langfristigen Zielen beiträgt.",
    "landingEisenhowerDecisionsTitle": "Bessere Entscheidungen",
    "landingEisenhowerDecisionsDesc": "Durch konsequente Anwendung der Matrix entwickeln Sie eine ergebnisorientierte Denkweise. Sie lernen, zu Ablenkungen \"Nein\" zu sagen und sich auf das zu konzentrieren, was echten Wert schafft.\n\nUnser digitales Werkzeug macht diesen Prozess sofort möglich: Ziehen Sie Aktivitäten in den richtigen Quadranten und erhalten Sie eine klare Übersicht Ihrer Prioritäten.",
    "landingEisenhowerBenefitsTitle": "Warum die Eisenhower-Matrix verwenden?",
    "landingEisenhowerBenefitsDesc": "Studien zeigen, dass 80% der täglichen Aktivitäten in die Quadranten 3 und 4 (nicht wichtig) fallen. Die Matrix hilft Ihnen, diese zu identifizieren und Zeit für das freizumachen, was wirklich zählt.",
    "landingEisenhowerQuadrants": "Quadrant 1: Dringend + Wichtig → Sofort erledigen\nQuadrant 2: Nicht dringend + Wichtig → Planen\nQuadrant 3: Dringend + Nicht wichtig → Delegieren\nQuadrant 4: Nicht dringend + Nicht wichtig → Eliminieren",
    "landingAgileBadge": "Methoden",
    "landingAgileTitle": "Agile & Scrum Framework",
    "landingAgileSubtitle": "Implementieren Sie die besten Praktiken der iterativen Softwareentwicklung",
    "landingAgileIterativeTitle": "Iterative und inkrementelle Entwicklung",
    "landingAgileIterativeDesc": "Der agile Ansatz teilt die Arbeit in kurze Zyklen namens Sprints auf, typischerweise 1-4 Wochen. Jede Iteration produziert ein funktionierendes Inkrement des Produkts.\n\nMit Keisen können Sie Ihr Backlog verwalten, Sprints planen und die Velocity des Teams in Echtzeit überwachen.",
    "landingAgileScrumTitle": "Scrum Framework",
    "landingAgileScrumDesc": "Scrum ist das verbreitetste agile Framework. Es definiert Rollen (Product Owner, Scrum Master, Team), Events (Sprint Planning, Daily, Review, Retrospektive) und Artefakte (Product Backlog, Sprint Backlog).\n\nKeisen unterstützt alle Scrum-Events mit dedizierten Werkzeugen für jede Zeremonie.",
    "landingAgileKanbanTitle": "Kanban Board",
    "landingAgileKanbanDesc": "Die Kanban-Methode visualisiert den Arbeitsfluss durch Spalten, die Prozesszustände darstellen. Sie begrenzt Work In Progress (WIP), um den Durchsatz zu maximieren.\n\nUnser Kanban Board unterstützt Spaltenanpassung, WIP-Limits und Flussmetriken.",
    "landingEstimationBadge": "Estimation",
    "landingEstimationTitle": "Kollaborative Schätztechniken",
    "landingEstimationSubtitle": "Wählen Sie die beste Methode für Ihr Team für genaue Schätzungen",
    "landingEstimationFeaturesTitle": "Estimation Room Funktionen",
    "landingRetroBadge": "Retrospective",
    "landingRetroTitle": "Interaktive Retrospektiven",
    "landingRetroSubtitle": "Kollaborative Echtzeit-Werkzeuge: Timer, anonyme Abstimmung, Aktionspunkte und KI-Berichte.",
    "landingRetroActionTitle": "Action Items Tracking",
    "landingRetroActionDesc": "Jede Retrospektive generiert nachverfolgbare Aktionspunkte mit Verantwortlichem, Frist und Status. Überwachen Sie die Nachverfolgung im Zeitverlauf.",
    "landingWorkflowBadge": "Workflow",
    "landingWorkflowTitle": "So funktioniert es",
    "landingWorkflowSubtitle": "Starten Sie in 3 einfachen Schritten",
    "landingStep1Title": "Erstellen Sie ein Projekt",
    "landingStep1Desc": "Erstellen Sie Ihr Agile-Projekt und laden Sie das Team ein. Konfigurieren Sie Sprints, Backlog und Board.",
    "landingStep2Title": "Zusammenarbeiten",
    "landingStep2Desc": "Schätzen Sie User Stories gemeinsam, organisieren Sie Sprints und verfolgen Sie den Fortschritt in Echtzeit.",
    "landingStep3Title": "Verbessern",
    "landingStep3Desc": "Analysieren Sie Metriken, führen Sie Retrospektiven durch und verbessern Sie den Prozess kontinuierlich.",
    "landingCtaTitle": "Ready to start?",
    "landingCtaDesc": "Melden Sie sich kostenlos an und beginnen Sie mit Ihrem Team zusammenzuarbeiten.",
    "landingFooterBrandDesc": "Kollaborative Werkzeuge für agile Teams.\nPlanen, schätzen und gemeinsam verbessern.",
    "landingFooterProduct": "Produkt",
    "landingFooterResources": "Ressourcen",
    "landingFooterCompany": "Unternehmen",
    "landingFooterLegal": "Rechtliches",
    "landingCopyright": "© 2026 Keisen. Alle Rechte vorbehalten.",
    "featureSmartImportDesc": "Schnelle Taskerstellung mit Beschreibung\nZuweisung an Teammitglieder\nKonfigurierbare Prioritäten und Fristen\nAbschlussbenachrichtigungen",
    "featureImportDesc": "Import aus CSV-Dateien\nKopieren/Einfügen aus Excel\nIntelligentes Text-Parsing\nAutomatisches Feld-Mapping",
    "featureShareDesc": "Einladungen per E-Mail\nKonfigurierbare Berechtigungen\nKommentare zu Tasks\nÄnderungsverlauf",
    "featureSmartTaskCreation": "Schnelle Taskerstellung",
    "featureTeamAssignment": "Teamzuweisung",
    "featurePriorityDeadline": "Prioritäten und Fristen",
    "featureCompletionNotifications": "Abschlussbenachrichtigungen",
    "featureCsvImport": "CSV-Import",
    "featureExcelPaste": "Excel kopieren/einfügen",
    "featureSmartParsing": "Intelligentes Parsing",
    "featureAutoMapping": "Automatisches Mapping",
    "featureEmailInvites": "E-Mail-Einladungen",
    "featurePermissions": "Konfigurierbare Berechtigungen",
    "featureTaskComments": "Task-Kommentare",
    "featureHistory": "Änderungsverlauf",
    "featureAdvancedFilters": "Erweiterte Filter",
    "featureFullTextSearch": "Volltextsuche",
    "featureSorting": "Sortierung",
    "featureTagsCategories": "Tags & Kategorien",
    "featureArchiving": "Archivierung",
    "featureSort": "Sortierung",
    "featureDataExport": "Datenexport",
    "landingIntroFeatures": "Sprint Planning mit Teamkapazität\nPriorisiertes Backlog mit Drag & Drop\nVelocity Tracking und Burndown Chart\nDaily Standup unterstützt",
    "landingAgileScrumFeatures": "Product Backlog mit Story Points\nSprint Backlog mit Task-Aufteilung\nIntegriertes Retrospektive-Board\nAutomatische Scrum-Metriken",
    "landingAgileKanbanFeatures": "Anpassbare Spalten\nWIP-Limits pro Spalte\nIntuitives Drag & Drop\nLead Time und Cycle Time",
    "landingEstimationPokerDesc": "Die klassische Methode: Jedes Mitglied wählt eine Karte (1, 2, 3, 5, 8...). Die Schätzungen werden gleichzeitig aufgedeckt, um Verzerrungen zu vermeiden.",
    "landingEstimationTShirtTitle": "T-Shirt Size",
    "landingEstimationTShirtSubtitle": "Relative Größen",
    "landingEstimationTShirtDesc": "Schnelle Schätzung mit Größen: XS, S, M, L, XL, XXL. Ideal für erstes Backlog Grooming oder wenn eine grobe Schätzung benötigt wird.",
    "landingEstimationPertTitle": "Three-Point (PERT)",
    "landingEstimationPertSubtitle": "Optimistisch / Wahrscheinlich / Pessimistisch",
    "landingEstimationPertDesc": "Statistische Technik: Jedes Mitglied gibt 3 Schätzungen ab (O, M, P). Die PERT-Formel berechnet die gewichtete Schätzung: (O + 4M + P) / 6.",
    "landingEstimationBucketTitle": "Bucket System",
    "landingEstimationBucketSubtitle": "Schnelle Kategorisierung",
    "landingEstimationBucketDesc": "User Stories werden vordefinierten \"Buckets\" zugeordnet. Optimal für die schnelle Schätzung großer Mengen von Items in Refinement-Sitzungen.",
    "landingEstimationChipHiddenVote": "Verdeckte Abstimmung",
    "landingEstimationChipTimer": "Konfigurierbarer Timer",
    "landingEstimationChipStats": "Echtzeit-Statistiken",
    "landingEstimationChipParticipants": "Bis zu 20 Teilnehmer",
    "landingEstimationChipHistory": "Schätzverlauf",
    "landingEstimationChipExport": "Ergebnisexport",
    "landingRetroTemplateStartStopTitle": "Start / Stop / Continue",
    "landingRetroTemplateStartStopDesc": "Das klassische Format: Was anfangen zu tun, was aufhören zu tun, was weiterhin tun.",
    "landingRetroTemplateMadSadTitle": "Mad / Sad / Glad",
    "landingRetroTemplateMadSadDesc": "Emotionale Retrospektive: Was hat uns wütend, traurig oder froh gemacht.",
    "landingRetroTemplate4LsTitle": "4L's",
    "landingRetroTemplate4LsDesc": "Liked, Learned, Lacked, Longed For - vollständige Sprint-Analyse.",
    "landingRetroTemplateSailboatTitle": "Sailboat",
    "landingRetroTemplateSailboatDesc": "Visuelle Metapher: Wind (Unterstützung), Anker (Hindernisse), Felsen (Risiken), Insel (Ziele).",
    "landingRetroTemplateWentWellTitle": "Went Well / To Improve",
    "landingRetroTemplateWentWellDesc": "Einfaches und direktes Format: Was gut lief und was zu verbessern ist.",
    "landingRetroTemplateDakiTitle": "DAKI",
    "landingRetroTemplateDakiDesc": "Drop, Add, Keep, Improve - konkrete Entscheidungen für den nächsten Sprint.",
    "landingRetroFeatureTrackingTitle": "Action Items Tracking",
    "landingRetroFeatureTrackingDesc": "Jede Retrospektive generiert nachverfolgbare Aktionspunkte mit Verantwortlichem, Frist und Status. Überwachen Sie die Nachverfolgung im Zeitverlauf.",
    "landingAgileSectionBadge": "Methoden",
    "landingAgileSectionTitle": "Agile & Scrum Framework",
    "landingAgileSectionSubtitle": "Implementieren Sie die besten Praktiken der iterativen Softwareentwicklung",
    "landingSmartTodoCollabTitle": "Kollaborative Tasklisten",
    "landingSmartTodoCollabDesc": "Smart Todo verwandelt das tägliche Aufgabenmanagement in einen fließenden und kollaborativen Prozess. Erstellen Sie Listen, weisen Sie Tasks Teammitgliedern zu und überwachen Sie den Fortschritt in Echtzeit.\n\nIdeal für verteilte Teams, die eine kontinuierliche Synchronisierung der zu erledigenden Aufgaben benötigen.",
    "landingSmartTodoCollabFeatures": "Schnelle Taskerstellung mit Beschreibung\nZuweisung an Teammitglieder\nKonfigurierbare Prioritäten und Fristen\nAbschlussbenachrichtigungen",
    "landingSmartTodoImportFeatures": "Import aus CSV-Dateien\nKopieren/Einfügen aus Excel\nIntelligentes Text-Parsing\nAutomatisches Feld-Mapping",
    "landingSmartTodoSharingTitle": "Teilen und Einladen",
    "landingSmartTodoSharingDesc": "Laden Sie Kollegen und Mitarbeiter per E-Mail zu Ihren Listen ein. Jeder Teilnehmer kann die zugewiesenen Tasks anzeigen, kommentieren und den Status aktualisieren.\n\nPerfekt für die Verwaltung abteilungsübergreifender Projekte mit externen Stakeholdern oder funktionsübergreifenden Teams.",
    "landingSmartTodoSharingFeatures": "Einladungen per E-Mail\nKonfigurierbare Berechtigungen\nKommentare zu Tasks\nÄnderungsverlauf",
    "landingSmartTodoChipFilters": "Erweiterte Filter",
    "landingSmartTodoChipSearch": "Volltextsuche",
    "landingSmartTodoChipSort": "Sortierung",
    "landingSmartTodoChipTags": "Tags und Kategorien",
    "landingSmartTodoChipArchive": "Archivierung",
    "landingSmartTodoChipExport": "Datenexport",
    "landingEisenhowerTitle": "Eisenhower-Matrix",
    "landingEisenhowerUrgentTitle": "Dringend vs. Wichtig",
    "landingEisenhowerUrgentDesc": "Die Eisenhower-Matrix, entwickelt vom 34. Präsidenten der Vereinigten Staaten Dwight D. Eisenhower, teilt Aktivitäten in vier Quadranten basierend auf zwei Kriterien ein: Dringlichkeit und Wichtigkeit.\n\nDieses Entscheidungsframework hilft zu unterscheiden, was sofortige Aufmerksamkeit erfordert und was zu langfristigen Zielen beiträgt.",
    "landingEisenhowerUrgentFeatures": "Quadrant 1: Dringend + Wichtig → Sofort erledigen\nQuadrant 2: Nicht dringend + Wichtig → Planen\nQuadrant 3: Dringend + Nicht wichtig → Delegieren\nQuadrant 4: Nicht dringend + Nicht wichtig → Eliminieren",
    "landingEisenhowerDecisionsFeatures": "Intuitives Drag & Drop\nTeam-Zusammenarbeit in Echtzeit\nVerteilungsstatistiken\nExport für Berichte",
    "landingEisenhowerUrgentLabel": "DRINGEND",
    "landingEisenhowerNotUrgentLabel": "NICHT DRINGEND",
    "landingEisenhowerImportantLabel": "WICHTIG",
    "landingEisenhowerNotImportantLabel": "NICHT WICHTIG",
    "landingEisenhowerDoLabel": "ERLEDIGEN",
    "landingEisenhowerDoDesc": "Krisen, Fristen, Notfälle",
    "landingEisenhowerPlanLabel": "PLANEN",
    "landingEisenhowerPlanDesc": "Strategie, Wachstum, Beziehungen",
    "landingEisenhowerDelegateLabel": "DELEGIEREN",
    "landingEisenhowerDelegateDesc": "Unterbrechungen, Meetings, E-Mails",
    "landingEisenhowerEliminateLabel": "ELIMINIEREN",
    "landingEisenhowerEliminateDesc": "Ablenkungen, Social Media, Zeitverschwendung",
    "landingFooterFeatures": "Funktionen",
    "landingFooterPricing": "Preise",
    "landingFooterChangelog": "Versionshinweise",
    "landingFooterRoadmap": "Roadmap",
    "landingFooterDocs": "Dokumentation",
    "landingFooterAgileGuides": "Agile-Leitfäden",
    "landingFooterBlog": "Blog",
    "landingFooterCommunity": "Community",
    "landingFooterAbout": "Über uns",
    "landingFooterContact": "Kontakt",
    "landingFooterJobs": "Karriere",
    "landingFooterPress": "Pressematerial",
    "landingFooterPrivacy": "Datenschutzerklärung",
    "landingFooterTerms": "Nutzungsbedingungen",
    "landingFooterCookies": "Cookie-Richtlinie",
    "landingFooterGdpr": "DSGVO",
}

# This is part 1 of translations. We'll add parts 2-5 in subsequent steps.
# For now, save part 1 to a temp file.
import pickle
with open('/tmp/de_translations_part1.pkl', 'wb') as f:
    pickle.dump(translations, f)

print(f"Part 1: {len(translations)} translations saved")
